a = int(input("Enter the first value: "))
b = int(input("Enter the second value: "))
print("The sum of the numbers is: ", a+b)
print("The difference of the numbers is: ", a-b)
print("The product of the numbers is: ", a*b)
print("The quotient of the numbers is: ", a/b)
print("the result of the floor division of the two numbers is: ", a//a)
print("The cube of first number is: ", a*a*a)
print("THe cube of the second number is: ", b*b*b)